server:
  port: 8082
  error:
    whitelabel:
      enabled: false

# ===============================
# CLIENT COMMON CONFIG
# ===============================
client:
  connection-timeout: 2000 # milli seconds
  read-timeout: 2000 # milli seconds
  response-timeout: 2000 # milli seconds
  max-in-memory-size: 10 #mega bytes

# ===============================
# LOGGING PROPERTIES
# ===============================
logging:
  level:
    com:
      reactive:
        invoice: INFO
